### ISSUE TITLE
Improve documentation around adding specific SKUs to the cart from within a recommendation. I.e a clothing size selector with an add to bag button. 

### ISSUE THREAD

**Issue by rorynosto** [Nosto/nosto-shopify#2]
Understand this will vary from store to store - but it would be good to give an overall outline of how to achieve this function that we can share with agencies and merchants alike. 
See below from Jacopo's Git for reference. 
https://gist.github.com/jacopo-nosto/d4cfecb9294814e8e78141f9c1fd013c

**Comment by mridang** [comment]
Moved this to the default wiki as this isn't Shopify specific. https://github.com/Nosto/docs-nosto-com/issues/37
